#!/usr/bin/env bash
# prints fizzbuzz
set -m
n=1
while [ $n -le 100 ];
      do
	a=$((n%3))
	if [ "$a" = 0 ];
	then
		b=$((n%5))
		if [ "$b" = 0 ];
		then
			echo "FizzBuzz"
		else
			echo "Fizz";
		fi
	elif [ $((n%5)) = 0 ];
	then
		echo "Buzz";
	else
		echo $n;
	fi
	n=$((n + 1))
done