#!/usr/bin/env bash
# print "best school" ten times in a while loop
n=0
while [ "$n" -le 9 ];
      do n=$((n + 1));
   if [ "$n" = 4 ];
   then
	  echo "bad luck";
   elif [ "$n" = 8 ];
   then
       echo "good luck"
   else
       echo "Best School";
   fi
done
