#!/usr/bin/env bash
# While loop with case-switch in shell script
n=0
while [ "$n" -le 19 ]
do
	n=$((n + 1))
	case $n in
		4)
			echo $n
			echo "bad luck from China"
			;;
		9)
			echo $n
			echo "bad luck from Japan"
			;;
		17)
			echo $n
			echo "bad luck from Italy"
			;;
		*)
			echo $n
			;;
      esac
done
