#!/usr/bin/env bash
# A script that installs firewall on server and sets some rules so that only traffic from SSH, HTTP and HTTPS is allowed.

sudo apt update -y
sudo apt install ufw -y
sudo ufw disable
sudo ufw reset
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw enable
